spring.application.name=nomina-portal-service
spring.datasource.url=jdbc:postgresql://localhost:5432/nomina-portal
spring.datasource.username=postgres
spring.datasource.password=nominapass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
server.port=8085
security.jwt.secret=CHANGE_ME_LONG_RANDOM_SECRET
security.jwt.expiration-seconds=86400
storage.base-path=C:/Users/VaheA/Desktop/
notifications.trademark.cron=0 0 9 * * *
notifications.design.cron=0 0 10 * * *
notifications.patent.cron=0 0 11 * * *
notifications.trademark.zone=UTC

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nomina.director@gmail.com
spring.mail.password=xdopjmtdomxhjboi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
notifications.mail.from=nomina.director@gmail.com
