spring.application.name=nomina-portal-service
spring.datasource.url=jdbc:postgresql://localhost:5432/nomina-portal
spring.datasource.username=postgres
spring.datasource.password=nominapass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
server.port=8085
security.jwt.secret=CHANGE_ME_LONG_RANDOM_SECRET
security.jwt.expiration-seconds=86400
storage.base-path=C:/Users/VaheA/Desktop/
